# Generated by Django 5.0.4 on 2024-04-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfastfood', models.CharField(max_length=25)),
                ('breakfastcalories', models.IntegerField()),
                ('breakfastprotein', models.IntegerField()),
                ('breakfastcarbohydrate', models.IntegerField()),
                ('breakfastfat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinnerfood', models.CharField(max_length=25)),
                ('dinnercalories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunchfood', models.CharField(max_length=25)),
                ('lunchcalories', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dEmailId', models.EmailField(max_length=254)),
                ('dbasePassword', models.CharField(max_length=25)),
            ],
        ),
    ]
