# Generated by Django 5.0.4 on 2024-04-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='dinnercarbohydrate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='dinnerfat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinner',
            name='dinnerprotein',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunch',
            name='lunchcarbohydrate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunch',
            name='lunchfat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lunch',
            name='lunchprotein',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='breakfastcarbohydrate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='breakfastfat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='breakfastprotein',
            field=models.FloatField(),
        ),
    ]
