# Generated by Django 5.0.4 on 2024-04-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_totalcaloriescalculate'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcaloriescalculate',
            name='name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
