# Generated by Django 5.0.4 on 2024-04-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_totalcaloriescalculate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcaloriescalculate',
            name='finalcalories',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
