# Generated by Django 5.0.4 on 2024-04-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_rename_name_totalcaloriescalculate_mailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='c',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailid', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('finalcalories', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='totalcaloriescalculate',
        ),
    ]
