# Generated by Django 5.0.4 on 2024-04-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_c_delete_totalcaloriescalculate'),
    ]

    operations = [
        migrations.CreateModel(
            name='caloriestarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emailid', models.CharField(max_length=25)),
                ('Age', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('Target', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='c',
        ),
    ]
