# Generated by Django 5.0.4 on 2024-05-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_caloriestarget_delete_c'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalcalories',
            name='Emailid',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
