# Generated by Django 5.0.4 on 2024-05-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_totalcalories_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalcalories',
            name='date',
            field=models.IntegerField(),
        ),
    ]
