# Generated by Django 5.0.4 on 2024-05-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_alter_totalcalories_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalcalories',
            name='date',
        ),
    ]
