# Generated by Django 5.0.4 on 2024-05-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0014_totalcalories_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalcalories',
            name='date',
            field=models.DateField(),
        ),
    ]
